# Generated by Django 2.2.4 on 2020-01-10 09:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Const',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('params', models.TextField(default="{\n    'key1': 'value1',\n    'key2': 'value2',\n    'key3': 'value3'\n}")),
            ],
        ),
    ]
