# Generated by Django 3.0.2 on 2020-06-16 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('const', '0003_auto_20200615_1226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='const',
            options={'verbose_name': 'Параметр', 'verbose_name_plural': 'Константы (Consts)'},
        ),
    ]
