# Generated by Django 3.0.2 on 2020-06-16 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0002_auto_20200615_1226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cake',
            options={'ordering': ['-updated'], 'verbose_name': 'Торт', 'verbose_name_plural': 'Торты (Cakes)'},
        ),
    ]
