# Generated by Django 3.0.2 on 2020-01-22 12:27

from django.db import migrations, models
import server.storage


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.ImageField(storage=server.storage.WebDavFileSystemStorage(), upload_to=''),
        ),
    ]
