# Generated by Django 3.0.2 on 2020-06-15 09:26

from django.db import migrations, models
import server.storage
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20200122_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Фото', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AlterField(
            model_name='photo',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.ImageField(storage=server.storage.WebDavFileSystemStorage(), upload_to='', verbose_name='Фото'),
        ),
    ]
